// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestGameDetective.API.Data;

#nullable disable

namespace QuestGameDetective.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260421110623_FixSeedData")]
    partial class FixSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.MurderCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KillerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ShortSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Victim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MurderCases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CauseOfDeath = "A gunshot wound to the head",
                            CrimeSceneDescription = "The library is panelled in dark oak, its tall bookshelves stretching up toward the ceiling.\nA dying fire crackles faintly in the hearth. Sir Reginald sits slumped in his leather armchair,\na revolver near his right hand and a half-finished glass of whisky on the side table.\nRain patters rhythmically against the tall window overlooking the quiet street.",
                            KillerIndex = 1,
                            Place = "His private library on Kensington Row",
                            Priority = 1,
                            ShortSummary = "A wealthy gentleman is found dead in his private library. Four individuals were inside the house that evening.",
                            SolutionText = "The revolver in the wrong hand makes suicide unlikely from the start. Several suspects tell small lies, but only one has a true motive.\n\nEdmund's story about writing letters collapses under scrutiny; he cannot recall simple details, and no such letter is found.\nFaced with the inconsistencies, he finally confesses — he shot Sir Reginald in the library to secure his inheritance.",
                            Title = "The Library Murder on Kensington Row",
                            Victim = "Sir Reginald Blackwood",
                            Weapon = "A small revolver found near his right hand."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CauseOfDeath = "Poisoning",
                            CrimeSceneDescription = "Thunder shakes the old manor as candles flicker along the long dining hall.\nLord Ashcroft lies collapsed at the head of the table, his untouched dessert before him.\nRain lashes against the tall windows, and the storm has knocked out the telephone lines.\nThe guests — all visibly shaken — stand gathered near the fireplace, each avoiding the others’ gaze.",
                            KillerIndex = 0,
                            Place = "The dining hall of Ashcroft Manor",
                            Priority = 2,
                            ShortSummary = "During a stormy night at the remote Ashcroft Manor, the master of the house dies during his own dinner party. Four guests remain under suspicion.",
                            SolutionText = "The wet hem of Lady Ashcroft’s dress contradicts her claim of staying inside the dining hall.\nShe slipped out during a clap of thunder, mixed arsenic into her husband’s wine, and returned unnoticed.\nDr. Graves could not have poisoned the wine from the study, and the Colonel and Miss Whitfield had no opportunity.\nWith mounting evidence and no alibi left standing, Lady Ashcroft ultimately confesses to the crime.",
                            Title = "The Midnight Tragedy at Ashcroft Manor",
                            Victim = "Lord Percival Ashcroft",
                            Weapon = "A crystal glass containing traces of arsenic"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CauseOfDeath = "Blunt force trauma",
                            CrimeSceneDescription = "The workshop is cluttered with intricate devices, the air filled with the steady ticking of dozens of clocks.\nTobias Wren lies face-down beside his workbench, a large brass gear stained with blood nearby.\nShards of glass cover the floor, and a single pocket watch ticks loudly from the victim’s hand.",
                            KillerIndex = 3,
                            Place = "His clockmaking shop in Covent Garden",
                            Priority = 0,
                            ShortSummary = "A famous clockmaker is found dead in his workshop among shattered gears and ticking mechanisms. Four individuals had business with him that evening.",
                            SolutionText = "The workshop door being locked suggests the killer exited through the back window.\nMrs. Finch insisted she was not present, yet brass dust on her gloves proves she had been inside the workshop.\nHer motive — unpaid rent — is the strongest among the suspects, and the tampered pocket watch was staged to mimic a struggle.\nConfronted with the inconsistencies, Mrs. Finch breaks down and confesses.",
                            Title = "The Clockmaker’s Last Hour in Covent Garden",
                            Victim = "Mr. Tobias Wren",
                            Weapon = "A heavy brass gear found on the floor beside the body"
                        });
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reminder1hSent")
                        .HasColumnType("bit");

                    b.Property<bool>("Reminder20hSent")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Label = "the butler",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mr. Hargreaves",
                            Statement = "\"I was in the kitchen, sir, listening to the wireless when the shot rang out — or so they tell me. I heard nothing at all.\""
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Label = "the nephew",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Edmund Blackwood",
                            Statement = "\"I spent the evening in the guest room, writing letters. I never left the room, I assure you.\""
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Label = "the housekeeper",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Beatrice Bloom",
                            Statement = "\"I was polishing the silver in the dining room. I did not go near the library, not once.\""
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            Label = "the neighbour",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Evelyn Ashdown",
                            Statement = "\"I left before the rain began. I heard nothing unusual, and the gentleman was quite well when I saw him last.\""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Label = "the widow",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Lady Imogen Ashcroft",
                            Statement = "\"Percival was in good health, I assure you. I only poured his wine, as I always do.\""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Label = "the family physician",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Lionel Graves",
                            Statement = "\"I stepped out to the study to fetch my medical kit. I returned only when I heard Lady Ashcroft scream.\""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Label = "the old friend",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Colonel Barnaby Holt",
                            Statement = "\"I was smoking in the conservatory. The thunder was so loud I heard nothing of the commotion inside.\""
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Label = "the governess",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Miss Clara Whitfield",
                            Statement = "\"I was preparing the children for bed and only came down when the staff called for me.\""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            Label = "the client",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Madame Valérie DuPont",
                            Statement = "\"I came to collect my repaired watch, but Mr. Wren told me it wasn’t ready. I left immediately.\""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-2222-2222-222222222222"),
                            Label = "the apprentice",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Arthur Bellamy",
                            Statement = "\"I stepped out for a smoke. When I returned, the door was locked from the inside.\""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            Label = "the officer",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Inspector Harold Briggs",
                            Statement = "\"I arrived to question Wren regarding a stolen heirloom. When I knocked, no one answered.\""
                        },
                        new
                        {
                            Id = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            Label = "the landlord",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Mrs. Adelaide Finch",
                            Statement = "\"He owed me two months’ rent, but I did not come here tonight. I was visiting my sister.\""
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuestGameDetective.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuestGameDetective.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGameDetective.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuestGameDetective.API.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.Suspect", b =>
                {
                    b.HasOne("QuestGameDetective.API.Models.MurderCase", null)
                        .WithMany("Suspects")
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.API.Models.MurderCase", b =>
                {
                    b.Navigation("Suspects");
                });
#pragma warning restore 612, 618
        }
    }
}
