// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestGameDetective.Infrastructure.Data;

#nullable disable

namespace QuestGameDetective.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515134926_UpdatedCaseContent")]
    partial class UpdatedCaseContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClueImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KillerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ShortSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Victim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MurderCases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CauseOfDeath = "En skottskada mot högra sidan av huvudet.",
                            ClueImg = "housemap.png",
                            CrimeSceneDescription = "Efter en noggrann undersökning kunde polisen inte finna några tecken på inbrott eller att någon obehörig tagit sig in i huset.\n\nVapnet identifierades snabbt som Sir Cedrics egen revolver. En tillhörande vapenkassett återfanns i skrivbordslådan.\n\nTrots detta kunde inget avskedsbrev eller annan förklaring till ett möjligt självmord hittas i vare sig biblioteket eller resten av fastigheten.\n\nInga värdesaker tycks heller ha försvunnit enligt tjänstefolket, och biblioteket visar inga tydliga spår av kamp eller genomsökning.\n\nVid första anblick framstår dödsfallet nästan som arrangerat.",
                            CrimeSceneImg = "crimescene.png",
                            KillerIndex = 1,
                            Place = "Sir Cedric återfanns död i sitt privata bibliotek på Kensington Row strax efter klockan 18 av husets butler.",
                            Priority = 1,
                            ShortSummary = "Den förmögne affärsmannen Sir Cedric Blackwood hittas död på golvet i sitt privata bibliotek under fredagskvällen.",
                            SolutionText = "Sir Cedric Blackwood mördades av sin brorson Edmund Blackwood, som var svårt skuldsatt och desperat i behov av pengar.\n\nEdmund hade nyligen flyttat in i herrgårdens gästrum efter att ha lyckats vinna sin farbrors förtroende.\n\nUnder förhören försökte Edmund beskriva den gamle mannen som trött, sjuklig och nedbruten, nästan som om han ville plantera tanken om självmord hos polisen.\n\nTjänstefolket motsäger dock detta och beskriver istället Sir Cedric som arbetsam och ovanligt skärpt för sin ålder.\n\nDen avgörande detaljen återfinns på brottsplatsen. Revolvern ligger vid offrets högra hand och skottskadan sitter på höger sida av huvudet.\n\nMen på skrivbordets vänstra sida ligger både penna och tekopp placerade på ett sätt som tydligt visar att Sir Cedric var vänsterhänt.\n\nEdmund, som endast bott i huset en kortare tid, kände aldrig till detta.",
                            Title = "Mordet i biblioteket på Kensington Row",
                            Victim = "Sir Cedric Blackwood",
                            VictimImg = "victim.png",
                            Weapon = "En liten revolver återfunnen nära offrets högra hand."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CauseOfDeath = "Förgiftning genom ett starkt sömnmedel som orsakat andningsstillestånd.",
                            ClueImg = "trainbag.png",
                            CrimeSceneDescription = "Kupédörren hade varit låst från insidan under större delen av natten och inga vittnen har sett någon lämna eller komma in.\n\nEndast fyra personer befann sig i kupén under resan: offret, Lady Eleanor Whitmore, hennes tjänsteflicka Clara Bennett samt den äldre pensionerade handelsmannen Harold Finch.\n\nOffret skall ha varit först i kupen och då luktat starkt av alkohol, han var då vi liv och hälsade men anningen sluddrigt när de andra klev in.\n\nTrots offrets enkla klädsel reste han i förstaklass, något flera vittnen på tåget beskrivit som ovanligt.\n\nIngen av de närvarande tycks känna offret sedan tidigare och samtliga hävdar att mannen var talförd och satt och läste tidningen när tåget lämnade London.",
                            CrimeSceneImg = "traincrime.png",
                            KillerIndex = 0,
                            Place = "Arthur Miller återfanns livlös i sin sittplats ombord på nattåget mot Edinburgh strax före gryningen.",
                            Priority = 2,
                            ShortSummary = "En man återfinns död i en förstaklasskupé under nattresan mellan London och Skottland.",
                            SolutionText = "Arthur Miller mördades av ... Arthur Miller. Mr Miller tog sitt eget liv vad polisen tror någon gång vid två på natten. \n\nIngen av de andra i hytten hade träffat offret sedan tidigare och hade såvidare inget med mannens död att göra.\n\nBara två veckor innan hade Mr Miller sökt vård för kraftiga smärtor i buken. Det visade sig att han var döende, läkaren gav honom knappt tre månader.\n\nI ett frösök att dämpa smärtorna som blev allt värre, snabbt fick han både smärtstillande tabletter och injeseringssprutor för när det blev för illa.'\n\nMr Miller som var krimialfantast vägrade att dö på ett så tråkigt sätt som i smärtor på ett sjukhus. Nej han ville lämna som mördad.\n\nHan lånade pengar av en bekant. Det räckte precis till en tågbiljett i första klass och en stor fin flaska wisky.\n\nEfter att alla i kupen somnat var det bara för honom att plocka fram sprutan, injesera sig själv, slänga ner och sparka till sprutan på golvet och luta sig tillbaka.\n\n",
                            Title = "Mysteriet på nattåget till Edinburgh",
                            Victim = "Arthur Miller",
                            VictimImg = "victim_train.png",
                            Weapon = "Gift som injicerats i offrets högra arm."
                        });
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reminder1hSent")
                        .HasColumnType("bit");

                    b.Property<bool>("Reminder20hSent")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InInvestigatorsNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspectImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            InInvestigatorsNotes = "Butlern uppträder korrekt och behärskat men blir märkbart obekväm när frågor om arv och familjekonflikter nämns.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mr. Hargreaves",
                            Role = "Butlern",
                            Statement = "Förhörsrapport:\n\n\"Jag befann mig i mitt rum på nedre våningen större delen av kvällen, sir. På fredagar brukar jag få några timmar ledigt.\n\nJag lyssnade på radion och hörde varken något skott eller något bråk. Ingen besökare kom heller till huset vad jag vet.\n\nSir Cedric brukade sitta ensam i biblioteket om kvällarna. Vid sextiden serverade jag honom som vanligt te — svart, utan socker.\"",
                            SuspectImg = "butler.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            InInvestigatorsNotes = "Edmund försöker framstå som lugn och hjälpsam men svarar undvikande på frågor om sin ekonomi och de brev han påstår sig ha skrivit.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Edmund Blackwood",
                            Role = "Brorsonen",
                            Statement = "Förhörsrapport:\n\n\"Jag tillbringade större delen av kvällen i gästrummet där jag skrev brev och försökte ordna mina affärer.\n\nMin farbror och jag hade naturligtvis våra meningsskiljaktigheter, men det hade nog vem som helst haft med en man som Sir Cedric.\n\nHan var gammal, envis och arbetade långt mer än vad hans hälsa tillät honom.\n\nJag vet inte om någon mördat honom eller om han själv valde att avsluta sitt liv.\n\nMen hushållerskan och min farbror grälade ofta. Jag hörde själv höjda röster tidigare samma morgon.\"",
                            SuspectImg = "nephew.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            InInvestigatorsNotes = "Hushållerskan verkar mer irriterad över polisförhöret än över själva dödsfallet. Samtidigt beskriver hon offret med oväntad uppriktighet.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Beatrice Bloom",
                            Role = "Hushållerskan",
                            Statement = "Förhörsrapport:\n\n\"Jag förstår fortfarande inte varför jag behövde tas hit till polisstationen. Folk kommer börja prata.\n\nJa, Sir Cedric kunde vara svår att ha att göra med, men det betyder inte att jag önskade livet ur honom.\n\nHan klagade på maten nästan varje dag trots att jag lagat mat åt fina familjer i över tjugo år.\n\nBönor och bacon ville han ha till förbannelse. Inte uppskattade han min korvomelett heller.\n\nMen arbete — det kunde den mannen. Inte ens åldern verkade få honom att sakta ner.\"",
                            SuspectImg = "housekeeper.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            InInvestigatorsNotes = "Det framstår som osannolikt att Sir Cedric frivilligt skulle avsluta sitt liv utan tydligare motiv eller avsked.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Sir Cedric Blackwood",
                            Role = "Offret",
                            Statement = "Polisens anteckningar:\n\nKan Sir Cedric Blackwood ha tagit sitt eget liv?\n\nNågot avskedsbrev har inte återfunnits och inget på brottsplatsen tyder på desperation eller förberedelser inför självmord.\n\nOffrets husläkare uppger att Sir Cedric nyligen sökt vård för åldersrelaterade besvär och försämrad hälsa, men ingen allvarlig diagnos hade fastställts.\n\nTrots sitt tillbakadragna sätt beskrivs han av tjänstefolket som disciplinerad, skarp och starkt fäst vid sitt arbete.\n\nSamtliga personer som bott under Sir Cedrics tak tycks bära på egna konflikter, ekonomiska problem eller personliga hemligheter.",
                            SuspectImg = "victim.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            InInvestigatorsNotes = "Lady Eleanor uppträder kyligt och kontrollerat men reagerar starkt när frågor om familj och tidigare relationer nämns.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Lady Eleanor Whitmore",
                            Role = "Överklassdam",
                            Statement = "Förhörsrapport:\n\n\"Jag reste mot Edinburgh för att besöka min syster, hennes makes bortgång har tagit mycket hårt på henne\n\nJag sovit? Sitandes? Sånt gör inte en Whitmore. Jag på min höjd blundade lite. Jag blir så åksju i tåg.\n\nDen döde mannen? Nej, jag har aldrig tidigare sett honom.\n\nJag måste dock erkänna att jag fann det märkligt att en så enkelt klädd person reste i förstaklass.\n\nNär jag var ung hade människor betydligt bättre förståelse för sin plats i samhället.\"",
                            SuspectImg = "trainlady.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            InInvestigatorsNotes = "Clara verkar nervös och undviker ögonkontakt. Det framstår mer som rädsla än skuld.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Clara Bennett",
                            Role = "Tjänsteflicka",
                            Statement = "Förhörsrapport:\n\n\"Jag har arbetat hos Lady Eleanor i ungefär ett år nu.\n\nInnan dess tjänade jag hos en familj i Brighton.\n\nJag talade aldrig med den döde mannen. Han läste mest under resan. Sen somnade jag ganska snart.\n\nLady Eleanor bad mig försöka sova eftersom vi hade en lång resa framför oss.\n\nJag tror Elenore somnade förre mig, hon snarkar lite förstår ni.\"",
                            SuspectImg = "trainmaid.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            InInvestigatorsNotes = "Harold Finch verkar ovanligt oberörd av situationen men hans berättelse förblir konsekvent under samtliga förhör.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Harold Finch",
                            Role = "Pensionerad handelsman",
                            Statement = "Förhörsrapport:\n\n\"Va? Ni måste tala högre konstapeln. Jag är nästan döv på höger öra oh ja vänster är väll inte mycket bättre. Jaha, mordet ja.\n\nJag sov större delen av resan, precis som jag alltid gör på tåg. Jag är gift förstår ni, så jag passar alltid på med att få vila när jag har chansen\n\nOberörd? Jag? Ja, när man nått mon åldern konstapeln så är det inte längre mycket som förvånar än. Jag har överlevt två världskrig och ett 40 årigt äktenskap. Då är det inte längre mycekt som får än att höja pulsen\n\nI London? Jag hade varit i London och hälsat på en gammal vän ifrån ungdomens dagar. Vi gick i skolan tillsammans.\n\nNej, jag känner ingen av de andra passagerarna. Tror knappt jag hört hälften av vad de sagt heller och nog är det likabra de.\"",
                            SuspectImg = "oldman.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            InInvestigatorsNotes = "Offret framstår vid första anblick som obetydlig men flera detaljer antyder en dold koppling till någon i kupén.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Arthur Miller",
                            Role = "Offret",
                            Statement = "Polisens anteckningar:\n\nArthur Miller bodde ensam i en mindre enrummare utanför London och arbetade sen en tid tillbaka i en bokaffär.\n\nHans ekomomi var mycket stram och gav inga möjligheter till annant än det nödvänigaste\n\nI hemmet återfanns knappa personliga tillhörigheter men ett stor antal böcker, uppskattningsvis 20-30 stycken fanns under hans säng.\n\nEfter samtal med en mycket upprörd arbetsgivare visade det sig att samtliga böcker tagits ifrån hans affär under loppet av fyra år.\n\nNästan alla böckerna var deckare, eller fackliteratur för krimonolgogi i olika former. Inga pengar hittades i bostade.",
                            SuspectImg = "victim_train.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", "MurderCase")
                        .WithMany()
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MurderCase");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", null)
                        .WithMany("Suspects")
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Navigation("Suspects");
                });
#pragma warning restore 612, 618
        }
    }
}
