// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestGameDetective.Infrastructure.Data;

#nullable disable

namespace QuestGameDetective.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260522201920_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClueImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClueImgText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneImgText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KillerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SecondClueImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecondClueImgText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionClues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Victim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimAge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimJob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimLifeSituation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MurderCases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CauseOfDeath = "En skottskada mot sidan av huvudet. Offret avled omedelbart.",
                            ClueImg = "housemap.png",
                            ClueImgText = "Planlösning över fastigheten",
                            CrimeSceneDescription = "Lord Cedric Blackwood påträffades död i sitt privata bibliotek av husets butler omkring halv nio på aftonen. Polisen anlände till herrgården kort därefter.\n\nDen avlidne låg livlös vid sitt skrivbord med en skottskada mot huvudet. Intill offrets högra hand återfanns en revolver, senare identifierad som tillhörande Lord Blackwood själv. (Se brottsplatsfotografi.)\n\nVapnets hölster återfanns i den översta byrålådan i biblioteket, vilket antyder att revolvern nyligen tagits fram.\n\nBiblioteket uppvisade inga tydliga tecken på strid, inbrott eller annan våldsam oordning. Detsamma gällde övriga delar av bostaden.\n\nPå golvet bakom skrivbordet återfanns dessutom ett handskrivet brev, vilket vid första anblick förefaller vara ett självmordsbrev. (Se fotografi — bevismaterial.)\n\nTrots detta framstår flera detaljer på brottsplatsen som märkligt arrangerade, vilket väcker misstanke om att dödsfallet inte är fullt så enkelt som det först verkar.",
                            CrimeSceneImg = "crimescene.png",
                            CrimeSceneImgText = "Brottsplatsfotografi – Biblioteket",
                            KillerIndex = 1,
                            Place = "Brottet begicks i offrets egen bostad, närmare bestämt i biblioteket.",
                            Priority = 1,
                            SecondClueImg = "LibraryMurder-Letter.png",
                            SecondClueImgText = "Självmordsbrevet som hittades på brottsplatsen",
                            ShortSummary = "Den förmögne affärsmannen Lord Cedric Blackwood hittas död på golvet i sitt privata bibliotek en fredagskväll.",
                            SolutionClues = "• På flera fotografier syns att Lord Blackwood konsekvent använde vänster hand vid skrivande och tedrickande.\n\n• På brottsplatsfotografiet återfanns revolvern placerad nära offrets högra hand trots att offret var vänsterhänt.\n\n• Självmordsbrevet uppvisar tydliga drag av att ha skrivits av en högerhänt person.\n\n• De övriga misstänkta hade känt Lord Blackwood i många år och var väl medvetna om hans vänsterhänthet.\n\n• Edmund Blackwood hade endast vistats i huset under en kortare tid och saknade samma kännedom om offrets vanor.",
                            SolutionText = "Lord Cedric Blackwood mördades av sin brorson Edmund Blackwood, som under en längre tid dragit på sig betydande skulder och såg sin farbror som sin sista möjlighet till ekonomisk räddning.\n\nUtredningen tog en avgörande vändning när det framkom att Lord Blackwood var vänsterhänt. På både skrivbordet och i övriga delar av biblioteket återfanns personliga föremål konsekvent placerade till vänster om honom.\n\nTrots detta återfanns revolvern intill offrets högra hand, och skottskadan tydde på att vapnet avfyrats från höger sida.\n\nDet handskrivna självmordsbrevet visade dessutom tydliga tecken på att ha skrivits av någon som använt höger hand.\n\nDe övriga misstänkta hade alla arbetat eller levt nära Lord Blackwood under många års tid och kände väl till hans vänsterhänthet. Edmund däremot hade endast vistats i huset under en kortare period.\n\nSammantaget pekar bevisningen mot att brottsplatsen medvetet arrangerats för att efterlikna ett självmord.",
                            Title = "Mordet i biblioteket på Kensington Row",
                            Victim = "Sir Cedric Blackwood",
                            VictimAge = "69 år",
                            VictimImg = "victim.png",
                            VictimJob = "Affärsman - Delägare",
                            VictimLifeSituation = "Levde i stor villa tillsammans med tjänstefolk och sin brorson. Mycket förmögen. Ogift och utan barn. Enda kvarvarande familj är hans bror och brorsbarn.",
                            Weapon = "Revolver som återfinns på brottsplatsen"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CauseOfDeath = "Andningsstillestånd orsakat av en kraftig överdos av morfinbaserat smärtstillande medel.",
                            ClueImg = "trainbag.png",
                            ClueImgText = "Innehållet i offrets väska",
                            CrimeSceneDescription = "Arthur Miller påträffades död strax före gryningen av konduktören under nattågets färd mot Edinburgh.\n\nKupédörren hade varit låst från insidan större delen av natten och inga vittnen hade sett någon lämna eller beträda kupén efter att tåget lämnat London.\n\nEndast tre andra personer befann sig i förstaklasskupén under resan: Lady Eleanor Whitmore, hennes tjänsteflicka Clara Bennett samt den pensionerade handelsmannen Harold Finch.\n\nOffret satt tillbakalutad i sin sittplats och såg vid första anblick ut att ha somnat. Först när konduktören försökte väcka mannen upptäcktes att han var avliden.\n\nEn mindre injektionsspruta återfanns senare under offrets säte. På offrets högra arm kunde dessutom ett mindre stickmärke observeras.\n\nTrots den ovanliga situationen återfanns inga tydliga tecken på kamp eller våld inne i kupén.\n\nFlera passagerare uppgav däremot att offret under kvällen luktat kraftigt av alkohol och verkat ovanligt avslappnad trots sin enkla klädsel och det dyra resesällskapet.",
                            CrimeSceneImg = "traincrime.png",
                            CrimeSceneImgText = "Brottsplatsfotografi – Förstaklasskupén",
                            KillerIndex = 4,
                            Place = "Brottet ägde rum ombord på nattåget mellan London och Edinburgh, i en låst förstaklasskupé.",
                            Priority = 1,
                            SecondClueImg = "doctorLetter.png",
                            SecondClueImgText = "Medicinsk handling hittas på offrets köksbord",
                            ShortSummary = "En man återfinns död i en låst förstaklasskupé under nattresan mellan London och Edinburgh.",
                            SolutionClues = "• En medicinsk spruta återfanns på golvet intill offret.\n\n• Ett läkarintyg återfanns bland offrets tillhörigheter som visade att han led av obotlig cancer.\n\n• Offret reste ensam i en förstaklasskupé trots att han vid första anblick verkade vara en man med mycket begränsade tillgångar.\n\n• På fotografiet av offrets resväska syns endast ett fåtal ägodelar: en dyr flaska whisky, flera kriminalromaner, mediciner samt ett mycket litet antal mynt.\n\n• Väskan var ovanligt sparsamt packad för en längre resa.",
                            SolutionText = "Arthur Miller mördades inte av någon av de övriga passagerarna. Mannen tog sitt eget liv någon gång under natten.\n\nUtredningen tog en avgörande vändning när polisens läkare kunde koppla den återfunna sprutan till ett kraftigt morfinbaserat läkemedel.\n\nVid vidare undersökning framkom att Arthur Miller endast två veckor tidigare diagnostiserats med en dödlig sjukdom och enligt läkarna hade mycket kort tid kvar att leva.\n\nI offrets bagage återfanns både medicinska dokument och smärtstillande preparat utskrivna i hans eget namn.\n\nArthur Miller var dessutom känd av sin arbetsgivare som en stor beundrare av kriminalromaner och verkliga mordutredningar.\n\nPolisen drog därför slutsatsen att mannen medvetet iscensatt sin egen död som ett till synes omöjligt mord ombord på nattåget.\n\nEfter att de övriga passagerarna somnat injicerade han själv läkemedlet, dolde sprutan under sätet och inväntade därefter döden.",
                            Title = "Mysteriet på nattåget till Edinburgh",
                            Victim = "Arthur Miller",
                            VictimAge = "43 år",
                            VictimImg = "victim_train.png",
                            VictimJob = "Butiksbiträde i bokhandel",
                            VictimLifeSituation = "Levde ensam i en mindre enrummare utanför London. Hade få nära relationer och mycket begränsad ekonomi.",
                            Weapon = "Medicinsk injektionsspruta återfunnen under offrets säte."
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CauseOfDeath = "Akut arsenikförgiftning.",
                            ClueImg = "tablebedroom.png",
                            ClueImgText = "Fotografi från Charlottes sovrum",
                            CrimeSceneDescription = "Den traditionella söndagsmiddagen hölls i den stora matsalen på Ravenshire Manor.\n\nNär huvudrätten serverades tog Charlotte Ashbourne några klunkar ur sitt vinglas innan hon plötsligt började hosta våldsamt och föll ihop över bordet.\n\nFamiljens läkare anlände kort därefter och kunde endast konstatera att den unga kvinnan redan var avliden.\n\nVid senare undersökning återfanns tydliga spår av arsenik i offrets vinglas. Inga övriga glas eller maträtter visade däremot tecken på förgiftning.\n\nVid middagsbordet befann sig offrets föräldrar, hennes två systrar, brodern Jonathan Ashbourne, Charlottes fästman Thomas Fairford samt systern Helenas fästman Julian Pembroke, som anlände sent till middagen.\n\nTrots familjens försök att beskriva relationerna som goda framkommer det snabbt under förhören att flera familjemedlemmar hyst stark bitterhet gentemot Charlotte under en längre tid.",
                            CrimeSceneImg = "familydinnercrime.png",
                            CrimeSceneImgText = "Brottsplatsfotografi – Middagsbordet efter dödsfallet",
                            KillerIndex = 1,
                            Place = "Ravenshire Manor, strax utanför London.",
                            Priority = 2,
                            SecondClueImg = "charlottediary.png",
                            SecondClueImgText = "Dagboks hittad under offrets säng",
                            ShortSummary = "Under en till synes stillsam familjemiddag faller den yngsta dottern plötsligt död ner efter att ha druckit ur sitt vinglas.",
                            SolutionClues = "• Endast Charlottes vinglas innehöll spår av arsenik.\n\n• Helena Ashbourne lämnade bordet ensam under middagen under förevändning att hämta mer vin.\n\n• På fotografiet från Charlottes sovrum syns en halvpackad resväska samt ett porträtt av Thomas Fairford.\n\n• Dagboksanteckningar återfunna i offrets rum visar att Charlotte planerade att bryta sin förlovning och rymma följande morgon.\n\n• På Helenas ring upptäcktes senare ett dolt fack innehållande rester av arsenik.",
                            SolutionText = "Charlotte Ashbourne mördades av sin syster Helena Ashbourne.\n\nUnder större delen av sitt liv hade Helena levt i skuggan av sin yngre syster, som ständigt behandlades som familjens favorit.\n\nNär Charlotte dessutom planerade att lämna Ravenshire Manor tillsammans med Thomas Fairford växte Helenas bitterhet till hat.\n\nHelena hade sedan flera veckor tillbaka införskaffat arsenik som hon gömde i ett dolt fack i sin ring.\n\nUnder middagen lämnade hon bordet under förevändning att hämta mer vin och passade då på att hälla giftet i Charlottes glas.\n\nCharlotte drack först av vinet när huvudrätten serverades.\n\nI Charlottes sovrum återfanns en halvpackad resväska, privata brev samt dagboksanteckningar som tydligt visade att hon planerade att rymma följande morgon.\n\nUnder det avslutande förhöret bröt Helena slutligen samman och erkände mordet.",
                            Title = "Familjemiddagsmordet på Ravenshire Manor",
                            Victim = "Charlotte Ashbourne",
                            VictimAge = "23 år",
                            VictimImg = "youngsistervictim.png",
                            VictimJob = "Överklassdam",
                            VictimLifeSituation = "Yngsta dottern i familjen Ashbourne. Levde ett skyddat liv på Ravenshire Manor men planerade i hemlighet att lämna familjens herrgård.",
                            Weapon = "Arsenik blandat i offrets vinglas."
                        });
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reminder1hSent")
                        .HasColumnType("bit");

                    b.Property<bool>("Reminder20hSent")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InInvestigatorsNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Job")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LifeSituation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspectImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Age = "52 år",
                            InInvestigatorsNotes = "Mr. Hargreaves verkar skakad, men blir märkbart upprörd när samtalet kommer in på hans syster.",
                            Job = "Arbetat som butler hela livet, de senaste 24 åren hos Lord Cedric Blackwood",
                            LifeSituation = "Aldrig gift, inga barn och bor i ett litet rum på nedervåningen. Enda familjen är en sjuk syster i Brighton.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mr. Hargreaves",
                            Role = "Offrets butler",
                            Statement = "Förhörsrapport:\n\n\"Jag befann mig i mitt rum på nedre våningen större delen av aftonen, sir. På fredagar brukar jag erhålla några timmars ledighet.\n\nI vanliga fall hade jag tagit mig en promenad till den lokala puben, men sedan min syster insjuknade går större delen av min lön till hennes uppehälle.\n\nHon blev änka tidigare i år, och inte långt därefter stupade hennes ende son i kriget. Nu är hon så svag att hon knappt förmår lämna sin säng.\n\nJag hade önskat flytta ned till Brighton för att finna arbete där och ta hand om henne, men Lord Blackwood vägrar låta mig lämna min tjänst.\n\nUtan ett ordentligt rekommendationsbrev från min arbetsgivare lär ingen vilja anställa mig.\n\nMen kanske nu… efter alla dessa år i hans tjänst. Kanske kommer min lojalitet äntligen att betyda något.\n\nMörda honom? Nej, sir — absolut inte. Lord Blackwood må ha varit en egendomlig herre, men någon ond man var han inte.\n\nJa, det var jag som fann honom. Eftersom jag ändå stannade inne den kvällen gick jag upp till biblioteket med en kopp te vid halv åtta.\n\nOch där låg han redan död.\n\nJag hörde inget skott under aftonen, men radion stod på större delen av eftermiddagen. Dessutom är huset mycket väl ljudisolerat.\"",
                            SuspectImg = "butler.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Age = "26 år",
                            InInvestigatorsNotes = "Edmund försöker framstå som lugn och hjälpsam men svarar undvikande på frågor om sin ekonomi och de brev han påstår sig ha skrivit.",
                            Job = "Arbetslös",
                            LifeSituation = "Blev utslängd av sin far för tre veckor sedan. Hans farbror Lord Cedric Blackwood tog in honom i sitt hem och lät honom bo i gästrummet.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Edmund Blackwood",
                            Role = "Offrets brorson",
                            Statement = "Förhörsrapport:\n\n\"Jag tillbringade större delen av aftonen i mitt rum, där jag skrev brev och ordnade vissa personliga angelägenheter.\n\nInte för att det egentligen angår er, sir, men jag har flera betydande affärer under uppsegling. Min far, liksom min farfar före honom, var båda framstående män inom affärsvärlden.\n\nVem jag skrev till är av privat natur och har inget med denna utredning att göra.\n\nAtt jag skulle ha mördat min farbror är fullständigt befängt. Lord Cedric tog emot mig i sitt hem efter att relationen mellan min far och mig blivit... ansträngd.\n\nDäremot kan jag inte förneka att både butlern och hushållerskan vid flera tillfällen låtit sin bitterhet över honom komma till uttryck när de trott sig vara ensamma.\n\nVad jag själv tror? Självmord.\n\nJag råkade överhöra några av polismännen tala om ett brev som påträffats i biblioteket. Ett självmordsbrev, om jag förstod saken rätt.\n\nMin farbror började bli en gammal man. Hälsan svek honom allt mer för varje månad som gick, och relationerna inom hushållet hade länge varit ansträngda.\n\nDet är en tragisk historia, sir. Men jag fruktar att hans dalande liv till sist blev för mycket för farbror.\"",
                            SuspectImg = "nephew.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Age = "61 år",
                            InInvestigatorsNotes = "Hushållerskan verkar mest irriterad och arg, men samtidigt uppriktig.",
                            Job = "Hushållerska, arbetat hela livet inom hushållstjänst och de senaste 15 åren hos Lord Cedric Blackwood",
                            LifeSituation = "Änka, en vuxen dotter. Bosatt i en liten etta ett stenkast från huset.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Beatrice Bloom",
                            Role = "Offrets hushållerska",
                            Statement = "Förhörsrapport:\n\n\"Jag förstår fortfarande inte varför jag behövde föras hit till polisstationen. Folk kommer börja tala, det är jag övertygad om.\n\nJa, Sir Cedric kunde stundtals vara en besvärlig herre att arbeta för, men det betyder inte att jag önskade livet ur honom.\n\nJag var förargad över honom de senaste veckorna. Han klagade ständigt på min mat och påstod att den gjorde honom sjuk. Fullständigt trams, om ni frågar mig.\n\nNågot skott hörde jag inte, nej. Men jag får medge att jag inte befann mig i huset under hela aftonen.\n\nVid halv sju höll jag på att förbereda kvällsmaten när jag råkade välta en hel kanna lingondricka över mina kläder.\n\nSå mellan halv sju och åtta befann jag mig hemma för att byta om. Något jag skäms en aning över att behöva erkänna.\n\nOch om ni frågar mig har det inte varit annat än bekymmer sedan den där slyngeln Edward flyttade in.\n\nTidigare under dagen var även Sir Victor Hawthorne där, Lord Blackwoods affärspartner. När jag stod i trappan kunde jag inte undgå att höra hur de grälade i biblioteket.\n\nHade jag varit i er sits, sir, hade jag tagit mig ett ordentligt samtal med honom också.\"",
                            SuspectImg = "housekeeper.png"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            Age = "66 år",
                            InInvestigatorsNotes = "Affärspartnern framstår som samlad och vältalig, men samtidigt märkbart skakad över sin gamle väns bortgång.",
                            Job = "Framstående affärsman",
                            LifeSituation = "Boende i stor herrgård tillsammans med sin hustru och tjänstefolk. Flera vuxna barn och en handfull barnbarn.",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Sir Victor Hawthorne",
                            Role = "Offrets affärspartner",
                            Statement = "Polisens anteckningar:\n\n\"Ja, det stämmer, konstapeln. Jag besökte Cedric tidigare under dagen. Jag tittade förbi på väg hem från arbetet.\n\nCedric brukade emellanåt arbeta hemifrån efter lunchtid, och först tänkte jag att den diskussion vi haft tidigare under dagen kunde vänta till efter helgen.\n\nMen jag ändrade mig under hemvägen. Cedric ville att vi skulle erbjuda arbete åt hans förbaskade brorson, och det hade jag inga som helst intentioner att gå med på.\n\nInte nog med att jag tvivlar starkt på att unge Edward någonsin utfört en ärlig dags arbete i hela sitt liv — det hade dessutom skapat problem inom firman.\n\nJag har nio barn, konstapeln. Tjugotvå barnbarn, varav åtminstone femton är i arbetsför ålder. Hur hade det sett ut om jag började dela ut tjänster enbart på grund av släktskap?\n\nFirman hade gått under innan året var slut, och det sade jag också till Cedric.\n\nNär allt väl lagts fram medgav han faktiskt att jag hade en poäng.\n\nSjälvmord, säger ni? Nej... det har jag svårt att tro.\n\nCedric var sitt vanliga reserverade jag. Något trött kanske, men fullt samlad. Vi skakade hand, sade att vi skulle ses igen på måndag, och därefter gick jag hem.\n\nRedan före klockan sex var jag tillbaka i mitt eget hus.\"",
                            SuspectImg = "workPartner.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Age = "58 år",
                            InInvestigatorsNotes = "Lady Eleanor uppträder kyligt och kontrollerat men verkar genuint obekväm av hela situationen.",
                            Job = "Överklassdam",
                            LifeSituation = "Tillhör en gammal aristokratisk familj och reser regelbundet mellan London och Edinburgh för att besöka släktingar.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Lady Eleanor Whitmore",
                            Role = "Passagerare i kupén",
                            Statement = "Förhörsrapport:\n\n\"Jag reste till Edinburgh för att besöka min syster. Hennes makes bortgång tidigare under året har tagit mycket hårt på henne.\n\nSova sittandes på ett tåg? Nej, konstapeln. Sådant må andra människor ägna sig åt. Jag vilade möjligen ögonen en stund.\n\nDen döde mannen hade jag aldrig tidigare sett.\n\nJag måste dock medge att jag fann det märkligt att en så enkelt klädd person reste i förstaklass.\n\nNär jag var ung hade människor en betydligt bättre förståelse för sin plats i samhället.\"",
                            SuspectImg = "trainlady.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Age = "21 år",
                            InInvestigatorsNotes = "Clara verkar nervös men hennes berättelse förblir konsekvent under förhöret.",
                            Job = "Tjänsteflicka",
                            LifeSituation = "Arbetar sedan ett år tillbaka åt Lady Eleanor Whitmore. Kommer ursprungligen från Brighton.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Clara Bennett",
                            Role = "Lady Eleanors tjänsteflicka",
                            Statement = "Förhörsrapport:\n\n\"Jag har arbetat hos Lady Eleanor i ungefär ett år nu.\n\nInnan dess tjänade jag hos en familj i Brighton.\n\nJag talade aldrig med den döde mannen. Han läste mest under resan och verkade hålla sig för sig själv.\n\nLady Eleanor sade åt mig att försöka sova eftersom vi hade en lång resa framför oss.\n\nJag tror faktiskt att hennes nåd somnade före mig. Hon snarkar lite ibland, förstår ni.\"",
                            SuspectImg = "trainmaid.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Age = "71 år",
                            InInvestigatorsNotes = "Harold Finch framstår som ovanligt lugn men hans berättelse innehåller inga tydliga motsägelser.",
                            Job = "Pensionerad handelsman",
                            LifeSituation = "Änkeman och pensionerad köpman. Bor ensam i utkanten av Edinburgh.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Harold Finch",
                            Role = "Passagerare i kupén",
                            Statement = "Förhörsrapport:\n\n\"Va? Ni får tala högre, konstapeln. Hörseln är inte vad den en gång var.\n\nJag sov större delen av resan, precis som jag alltid gör på tåg.\n\nOberörd? Nej då, men när man nått min ålder är det inte mycket som längre förvånar en.\n\nJag har överlevt två krig och fyrtio års äktenskap. Då lär man sig hålla huvudet kallt.\n\nI London besökte jag en gammal vän från ungdomens dagar. Vi gick i skolan tillsammans.\n\nNej, jag kände inte den döde mannen och knappt någon av de andra passagerarna heller.\"",
                            SuspectImg = "oldman.png"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Age = "31 år",
                            InInvestigatorsNotes = "Dr. Charles Mortimer framstår som uppriktigt förfärad över vad som inträffat. Under förhöret uppträder han nervöst men samarbetsvilligt och inga tydliga motsägelser framkommer.",
                            Job = "Läkare",
                            LifeSituation = "Gift och far till tre barn. Har praktiserat som läkare i sju år. Känd som ordningsam och har aldrig tidigare varit i kontakt med polisen.",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Charles Mortimer",
                            Role = "Offrets läkare",
                            Statement = "Förhörsrapport:\n\n\"Ja, det stämmer, konstapeln. Jag var Arthur Millers läkare, även om jag inte behandlat honom särskilt länge.\n\nMr Miller sökte först vård för återkommande buksmärtor. Efter mina inledande undersökningar remitterade jag honom vidare till en specialistklinik i London.\n\nDet visade sig dessvärre att han led av långt framskriden cancer.\n\nSjukdomen hade redan gått mycket långt och läkarna gav honom endast en kort tid kvar att leva.\n\nJa, jag skrev ut både smärtstillande tabletter och morfininjektioner för att hjälpa honom hantera smärtorna.\n\nMen jag försäkrar er, konstapeln, att all medicinering skedde helt enligt medicinska rekommendationer för patienter i hans tillstånd.\n\nDet är en fruktansvärd tragedi alltihop.\n\nMr Miller verkade visserligen nedstämd vid vårt senaste möte, men jag hade aldrig kunnat föreställa mig något sådant här.\"",
                            SuspectImg = "doctor.png"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-1111-1111-1111-111111111111"),
                            Age = "31 år",
                            InInvestigatorsNotes = "Jonathan uppträder arrogant men verkar samtidigt genuint skakad över systerns död.",
                            Job = "Arvtagare",
                            LifeSituation = "Spelberoende och svårt skuldsatt efter flera misslyckade investeringar.",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Jonathan Ashbourne",
                            Role = "Brodern",
                            Statement = "Förhörsrapport:\n\n\"Charlotte och jag stod aldrig varandra särskilt nära.\n\nHon var yngst och kom undan med precis allting.\n\nMor avgudade henne och far behandlade henne som om hon vore någon sorts prinsessa.\n\nJag vill inte ens veta hur mycket pengar som lagts på hennes nöjen genom åren.\n\nMen tro inte att det betyder att jag önskade henne död.\n\nMina föräldrar är gamla och redan svaga. Det här kommer ta livet av dem.\n\nJag reste mig aldrig från bordet under middagen och jag rörde aldrig hennes glas.\n\nOch ja, jag spelar ibland. Men spelare och mördare är inte samma sak, konstapeln.\"",
                            SuspectImg = "dinnerbrother.png"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-2222-2222-2222-222222222222"),
                            Age = "27 år",
                            InInvestigatorsNotes = "Helena framstår som känslomässigt instabil men försöker hela tiden behålla kontrollen över sig själv.",
                            Job = "Överklassdam",
                            LifeSituation = "Bor fortfarande kvar på familjens herrgård och lever under sin fars strikta kontroll.",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Helena Ashbourne",
                            Role = "Mellersta systern",
                            Statement = "Förhörsrapport:\n\n\"Charlotte hade ett märkligt sätt att få hela världen att kretsa kring henne.\n\nMor och far såg henne nästan som någon sorts liten ängel.\n\nDet är nästan skrattretande när man tänker på det.\n\nMen trots våra meningsskiljaktigheter var hon fortfarande min syster.\n\nJa, jag gick bort mot serveringsbordet under middagen men endast för att hämta mer vin.\n\nNär jag kom tillbaka började far hosta igen och sedan… sedan föll Charlotte ihop.\n\nAllting gick så fruktansvärt fort.\"",
                            SuspectImg = "sister1.png"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-3333-3333-3333-333333333333"),
                            Age = "29 år",
                            InInvestigatorsNotes = "Thomas verkar uppriktigt förtvivlad men flera familjemedlemmar beskriver relationen som betydligt mindre lycklig än han själv påstår.",
                            Job = "Banktjänsteman",
                            LifeSituation = "Förlovad med Charlotte Ashbourne men relationen beskrivs som turbulent av flera familjemedlemmar.",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Thomas Fairford",
                            Role = "Fästmannen",
                            Statement = "Förhörsrapport:\n\n\"Charlotte och jag planerade att gifta oss innan årets slut.\n\nÅtminstone var det planen.\n\nVi har haft våra gräl den senaste tiden men jag älskade henne verkligen.\n\nJag satt intill henne under hela middagen och jag såg ingen röra hennes glas.\n\nMen sådant är kanske heller inget man lägger märke till under en vanlig familjemiddag.\n\nJag vet bara att hon plötsligt började hosta och sedan… sedan var hon borta.\n\nJag skulle aldrig kunna skada Charlotte. Aldrig.\"",
                            SuspectImg = "tablefiance.png"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-4444-4444-4444-444444444444"),
                            Age = "35 år",
                            InInvestigatorsNotes = "Margaret verkar nervös men hennes berättelse förblir konsekvent genom hela utredningen.",
                            Job = "Överklassdam",
                            LifeSituation = "Äldsta systern i familjen. Har aldrig gift sig och fungerar ofta som medlare mellan familjemedlemmarna.",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Margaret Ashbourne",
                            Role = "Äldre systern",
                            Statement = "Förhörsrapport:\n\n\"Jag vill bara att det här skall vara över.\n\nCharlotte kunde vara svår ibland men hon förtjänade inte detta.\n\nBortskämd? Ja, kanske.\n\nMen det var mer mors och fars fel än hennes.\n\nJag såg Helena lämna bordet under middagen. Hon sade att hon skulle hämta mer vin men hon verkade snarare upprörd.\n\nHelenas fästman Julian anlände dessutom sent till middagen.\n\nIngen av mina systrar tycks ha varit särskilt lyckliga.\n\nOch folk frågar fortfarande varför jag valt att förbli ogift.\"",
                            SuspectImg = "bigsister2.png"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", "MurderCase")
                        .WithMany()
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MurderCase");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", null)
                        .WithMany("Suspects")
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Navigation("Suspects");
                });
#pragma warning restore 612, 618
        }
    }
}
