// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuestGameDetective.Infrastructure.Data;

#nullable disable

namespace QuestGameDetective.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseOfDeath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrimeSceneDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KillerIndex")
                        .HasColumnType("int");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ShortSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Victim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weapon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MurderCases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CauseOfDeath = "A gunshot wound to the head",
                            CrimeSceneDescription = "The library is panelled in dark oak...",
                            KillerIndex = 1,
                            Place = "His private library on Kensington Row",
                            Priority = 1,
                            ShortSummary = "A wealthy gentleman is found dead in his private library.",
                            SolutionText = "The revolver in the wrong hand makes suicide unlikely...",
                            Title = "The Library Murder on Kensington Row",
                            Victim = "Sir Reginald Blackwood",
                            Weapon = "A small revolver found near his right hand."
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CauseOfDeath = "Poisoning",
                            CrimeSceneDescription = "...",
                            KillerIndex = 0,
                            Place = "The dining hall of Ashcroft Manor",
                            Priority = 2,
                            ShortSummary = "During a stormy night...",
                            SolutionText = "...",
                            Title = "The Midnight Tragedy at Ashcroft Manor",
                            Victim = "Lord Percival Ashcroft",
                            Weapon = "A crystal glass containing traces of arsenic"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CauseOfDeath = "Blunt force trauma",
                            CrimeSceneDescription = "...",
                            KillerIndex = 3,
                            Place = "His clockmaking shop in Covent Garden",
                            Priority = 0,
                            ShortSummary = "A famous clockmaker is found dead...",
                            SolutionText = "...",
                            Title = "The Clockmaker’s Last Hour in Covent Garden",
                            Victim = "Mr. Tobias Wren",
                            Weapon = "A heavy brass gear found on the floor beside the body"
                        });
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Reminder1hSent")
                        .HasColumnType("bit");

                    b.Property<bool>("Reminder20hSent")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Quests");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MurderCaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MurderCaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-1111-1111-1111-111111111111"),
                            Label = "the butler",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mr. Hargreaves",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-2222-2222-2222-222222222222"),
                            Label = "the nephew",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Edmund Blackwood",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-3333-3333-3333-333333333333"),
                            Label = "the housekeeper",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Beatrice Bloom",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-4444-4444-4444-444444444444"),
                            Label = "the neighbour",
                            MurderCaseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Mrs. Evelyn Ashdown",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-1111-1111-1111-111111111111"),
                            Label = "the widow",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Lady Imogen Ashcroft",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-2222-2222-2222-222222222222"),
                            Label = "the family physician",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Dr. Lionel Graves",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-3333-3333-3333-333333333333"),
                            Label = "the old friend",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Colonel Barnaby Holt",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-4444-4444-4444-444444444444"),
                            Label = "the governess",
                            MurderCaseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Miss Clara Whitfield",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-1111-1111-1111-111111111111"),
                            Label = "the client",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Madame Valérie DuPont",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-2222-2222-2222-222222222222"),
                            Label = "the apprentice",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Arthur Bellamy",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-3333-3333-3333-333333333333"),
                            Label = "the officer",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Inspector Harold Briggs",
                            Statement = "..."
                        },
                        new
                        {
                            Id = new Guid("cccccccc-4444-4444-4444-444444444444"),
                            Label = "the landlord",
                            MurderCaseId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Name = "Mrs. Adelaide Finch",
                            Statement = "..."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Quest", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", "MurderCase")
                        .WithMany()
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MurderCase");
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.Suspect", b =>
                {
                    b.HasOne("QuestGameDetective.Domain.Entities.MurderCase", null)
                        .WithMany("Suspects")
                        .HasForeignKey("MurderCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestGameDetective.Domain.Entities.MurderCase", b =>
                {
                    b.Navigation("Suspects");
                });
#pragma warning restore 612, 618
        }
    }
}
